apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-data
  namespace: jenkins
  labels:
    app: pv-jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-jenkins-data
